### ISSUE TITLE
admin should not be able to see links to all ballots

### ISSUE THREAD

**Issue by gkop** [coshx/green-eggs#4]

**Comment by btaitelb** [comment]
Personally, I like being able to see how everyone voted. Maybe the way to do this is to drill down into the results rather than seeing individual ballots, so that they're anonymized?

**Comment by gkop** [comment]
Yeah, there's much better ways to visualize the breakdown than by
clicking through individual ballots anyway.

On Mon, Aug 29, 2011 at 1:30 PM, btaitelb
reply@reply.github.com
wrote:
